ALTER TABLE leads ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20);
ALTER TABLE products ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS mapped_product_id BIGINT REFERENCES products(id) ON DELETE SET NULL;
